### ISSUE TITLE
Yarn install error - node-gyp libudev.h

### ISSUE THREAD

**Issue by jurosh** [GetScatter/ScatterDesktop#156]
Trying to install scatter using yarn:

```
yarn     
yarn install v1.10.1
(node:16107) ExperimentalWarning: The fs.promises API is experimental
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[10/14] ⠂ chromedriver
[2/14] ⠂ usb
[7/14] ⠂ scrypt
[4/14] ⠄ secp256k1
error /home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@10.1.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding/usb_bindings.node" (not found)
node-pre-gyp http GET https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v64-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v64-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v64-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.3 and node@10.1.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v64-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.1.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.1.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jurosh/.node-gyp/10.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jurosh/.node-gyp/10.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/jurosh/.node-gyp/10.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.1.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
 #include <libudev.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [libusb.target.mk:140: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Linux 4.18.0-10-generic
gyp ERR! command "/home/jurosh/.nvm/versions/node/v10.1.0/bin/node" "/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/jurosh/.nvm/versions/node/v10.1.0/bin/node /home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp ERR! System Linux 4.18.0-10-generic
node-pre-gyp ERR! command "/home/jurosh/.nvm/versions/node/v10.1.0/bin/node" "/home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/jurosh/xyz/ScatterDesktop-9.5.0/node_modules/usb
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
```
Local setup on Ubuntu:

yarn `1.10.1`
node `v10.1.0`

**Comment by nsjames** [comment]
Try downgrading node to 8.9.0

**Comment by jurosh** [comment]
Same issue with `8.9.0` :-(

**Comment by nsjames** [comment]
Post the new error output please

**Comment by jurosh** [comment]
```
nvm use 8.9.0
Now using node v8.9.0 (npm v5.5.1)
jurosh@jurosh:~/Work/xyz/ScatterDesktop-9.5.0$ yarn
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[10/14] ⠂ chromedriver
[2/14] ⠂ usb
[7/14] ⠂ scrypt
[4/14] ⠂ secp256k1
error /home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@8.9.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding/usb_bindings.node" (not found)
node-pre-gyp http GET https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v57-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v57-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v57-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.3 and node@8.9.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/tessel/node-usb/releases/download/1.3.3/usb_bindings-v1.3.3-node-v57-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.9.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.9.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/jurosh/.node-gyp/8.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/jurosh/.node-gyp/8.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/jurosh/.node-gyp/8.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.9.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: Adresár alebo súbor neexistuje
 #include <libudev.h>
          ^~~~~~~~~~~
compilation terminated.
make: *** [libusb.target.mk:140: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.18.0-10-generic
gyp ERR! command "/home/jurosh/.nvm/versions/node/v8.9.0/bin/node" "/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd /home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/jurosh/.nvm/versions/node/v8.9.0/bin/node /home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/src/binding --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.18.0-10-generic
node-pre-gyp ERR! command "/home/jurosh/.nvm/versions/node/v8.9.0/bin/node" "/home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/jurosh/Work/xyz/ScatterDesktop-9.5.0/node_modules/usb
node-pre-gyp ERR! node -v v8.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/home/jurosh/.nvm/versions/node/v8.9.0/bin/node /home/jurosh/Work/xyz/ScatterDesktop-9.5.0/nod
```

**Comment by nsjames** [comment]
Try running `sudo apt-get install libusb-1.0-0-dev`

It looks like it's saying libusb doesn't exist.

**Comment by nsjames** [comment]
You'll also need to do `sudo apt-get install libudev-dev`

The reason for this is because of Ledger support which uses `usb` underneath that has native prebuilds which allows it to run in a nodejs environment.
