### ISSUE TITLE
run electron . failed

### ISSUE THREAD

**Issue by wenji-my** [GetScatter/ScatterDesktop#159]
App threw an error during load
        Error: The module '/Users/hua/projects/scatter-        projects/ScatterDesktop/node_modules/usb/src/binding/usb_bindings.node'
        was compiled against a different Node.js version using
        NODE_MODULE_VERSION 57. This version of Node.js requires
        NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
        the module (for instance, using `npm rebuild` or `npm install`).
            at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
            at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
            at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
            at Module.load (internal/modules/cjs/loader.js:620:32)
            at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
            at Function.Module._load (internal/modules/cjs/loader.js:551:3)
            at Module.require (internal/modules/cjs/loader.js:658:17)
            at require (internal/modules/cjs/helpers.js:20:18)
            at Object.<anonymous> (/Users/hua/projects/scatter-projects/ScatterDesktop/node_modules/usb/usb.js:5:38)
            at Object.<anonymous> (/Users/hua/projects/scatter-        projects/ScatterDesktop/node_modules/usb/usb.js:417:3)

**Comment by nsjames** [comment]
please post the results from this:

`node -v`
and 
`electron -v`

**Comment by wenji-my** [comment]
node: v10.12.0
electron: v3.0.6
What"s the cause for that？

**Comment by nsjames** [comment]
Try downgrading node to 8.9.0 and electron global to 1.8.2

**Comment by Alykoff** [comment]
```
node 10.10.0 
electron 1.8.2
```
works for me

**Comment by wenji-my** [comment]
> Try downgrading node to 8.9.0 and electron global to 1.8.2
It's right!Thank you!

**Comment by nsjames** [comment]
I went ahead and added this info to the README so that others wont have to look through the tickets to find it.
