### ISSUE TITLE
Can't compile on Arch Linux too many errors on sh, ELIFECYCLE, ENOENT spawn, etc.

### ISSUE THREAD

**Issue by Jzarecta** [GetScatter/ScatterDesktop#170]
Get the following log output
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v11.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle scatter@9.6.0~prebuild: scatter@9.6.0
6 info lifecycle scatter@9.6.0~build: scatter@9.6.0
7 verbose lifecycle scatter@9.6.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle scatter@9.6.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/jza/Downloads/ScatterDesktop/node_modules/.bin:/home/jza/perl5/bin:/home/jza/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/jza/.rvm/bin
9 verbose lifecycle scatter@9.6.0~build: CWD: /home/jza/Downloads/ScatterDesktop
10 silly lifecycle scatter@9.6.0~build: Args: [ '-c',
10 silly lifecycle   'concurrently "npm run copybuildfiles" "node build/build.js"' ]
11 info lifecycle scatter@9.6.0~build: Failed to exec build script
12 verbose stack Error: scatter@9.6.0 build: `concurrently "npm run copybuildfiles" "node build/build.js"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:970:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
13 verbose pkgid scatter@9.6.0
14 verbose cwd /home/jza/Downloads/ScatterDesktop
15 verbose Linux 4.18.16-arch1-1-ARCH
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
17 verbose node v11.1.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error scatter@9.6.0 build: `concurrently "npm run copybuildfiles" "node build/build.js"`
23 error spawn ENOENT
24 error Failed at the scatter@9.6.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by nsjames** [comment]
Seems like this was an issue with yarn not pulling in the `copyfiles` package. Closing as we resolved on telegram by just running `node build/build.js` by itself.
