### ISSUE TITLE
Error: connect ETIMEDOUT 52.216.0.88:443

### ISSUE THREAD

**Issue by wenji-my** [GetScatter/ScatterDesktop#250]
Hello, I got an error when I install the packages:
````
...
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/0_/7nskyqwj0vq8ssh70vcnsmx40000gq/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...

Error making request.
Error: connect ETIMEDOUT 52.216.0.88:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
````
What's the reason for that?

**Comment by nsjames** [comment]
This looks like just a connection issue with NPM and not anything to do with Scatter.
Might want to check on that package itself.
