### ISSUE TITLE
unknown type name 'secp256k1_context' during yarn install on macOS

### ISSUE THREAD

**Issue by robrigo** [GetScatter/ScatterDesktop#319]
Having an issue attempting to install dependencies for ScatterDesktop on macOS 10.14.4. I thought the issue may be related to missing xcode utilities so I updated and installed additional packages and CLI tools using `xcode-select --install`, but the error was still produced. I noticed that the pinned package version in package.json for electron is different from the one recommended in the README.

Full output below:

```
robs-MacBook-Pro:ScatterDesktop rob$ yarn install
yarn install v1.15.2
warning ../package.json: No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
$ electron-rebuild --force
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@9.8.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/rob/dev/ScatterDesktop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/dev/ScatterDesktop/node_modules/secp256k1/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/dev/ScatterDesktop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/.electron-gyp/.node-gyp/iojs-2.0.12/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rob/.electron-gyp/.node-gyp/iojs-2.0.12',
gyp info spawn args   '-Dnode_gyp_dir=/Users/rob/dev/ScatterDesktop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/rob/.electron-gyp/.node-gyp/iojs-2.0.12/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rob/dev/ScatterDesktop/node_modules/secp256k1',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/secp256k1/src/addon.o
../src/addon.cc:11:1: error: unknown type name 'secp256k1_context'; did you mean 'secp256k1_context_t'?
secp256k1_context* secp256k1ctx;
^~~~~~~~~~~~~~~~~
secp256k1_context_t
/usr/local/include/secp256k1.h:50:41: note: 'secp256k1_context_t' declared here
typedef struct secp256k1_context_struct secp256k1_context_t;
                                        ^
1 error generated.
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rob/dev/ScatterDesktop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/rob/.nvm/versions/node/v9.8.0/bin/node" "/Users/rob/dev/ScatterDesktop/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=2.0.12" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Users/rob/dev/ScatterDesktop/node_modules/secp256k1
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@9.8.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/rob/dev/ScatterDesktop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/dev/ScatterDesktop/node_modules/secp256k1/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/dev/ScatterDesktop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/rob/.electron-gyp/.node-gyp/iojs-2.0.12/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/rob/.electron-gyp/.node-gyp/iojs-2.0.12',
gyp info spawn args   '-Dnode_gyp_dir=/Users/rob/dev/ScatterDesktop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/rob/.electron-gyp/.node-gyp/iojs-2.0.12/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/rob/dev/ScatterDesktop/node_modules/secp256k1',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/secp256k1/src/addon.o
../src/addon.cc:11:1: error: unknown type name 'secp256k1_context'; did you mean 'secp256k1_context_t'?
secp256k1_context* secp256k1ctx;
^~~~~~~~~~~~~~~~~
secp256k1_context_t
/usr/local/include/secp256k1.h:50:41: note: 'secp256k1_context_t' declared here
typedef struct secp256k1_context_struct secp256k1_context_t;
                                        ^
1 error generated.
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rob/dev/ScatterDesktop/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/rob/.nvm/versions/node/v9.8.0/bin/node" "/Users/rob/dev/ScatterDesktop/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=2.0.12" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Users/rob/dev/ScatterDesktop/node_modules/secp256k1
gyp ERR! node -v v9.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.error (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:201:26)
    at Subscriber._error (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at Subscriber.error (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:106:18)
    at SafeSubscriber._next (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrSetError (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:251:16)
    at SafeSubscriber.next (/Users/rob/dev/ScatterDesktop/node_modules/spawn-rx/node_modules/rxjs/Subscriber.js:191:27)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by nsjames** [comment]
Cleaning tickets for Scatter 11 testing release (makes this ticket no longer relevant)

(new electron and node version, likely fixes this)
