### ISSUE TITLE
Occasional error logging into dapp - captured debug output in Scatter Desktop

### ISSUE THREAD

**Issue by acoutts** [GetScatter/ScatterDesktop#321]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```
```
$ uname -r
4.15.0-47-generic
```

```
Scatter Desktop: v10.1.2
"scatterjs-core": "^2.7.16",
"scatterjs-plugin-eosjs2": "^1.5.0",
```

Occasionally when I try to log into a dapp the login routine never returns or throws an error and hangs on the app side (scatterjs-core).

In scatter desktop, the following error is printed when this happens:
```
Uncaught (in promise) TypeError: Cannot read property 'hasOwnProperty' of null
    at Function.value (file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/app.30252fd8473870bd2a72.js:1:595244)
    at Function.<anonymous> (file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/app.30252fd8473870bd2a72.js:1:625518)
    at _ (file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/vendor.352f448180d031a732bb.js:24:334019)
    at Generator._invoke (file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/vendor.352f448180d031a732bb.js:24:333807)
    at Generator.t.(anonymous function) [as next] (file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/vendor.352f448180d031a732bb.js:24:334198)
    at n (file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/vendor.352f448180d031a732bb.js:75:278607)
    at file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/vendor.352f448180d031a732bb.js:75:278748
    at new Promise (<anonymous>)
    at new e (file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/vendor.352f448180d031a732bb.js:93:63922)
    at file:///tmp/.mount_linux-kmiS58/resources/app.asar/dist/static/js/vendor.352f448180d031a732bb.js:75:278542
```

![Screenshot from 2019-04-23 15-57-52](https://user-images.githubusercontent.com/9597207/56611742-934eb780-65e0-11e9-9a64-c223602487f0.png)

**Comment by nsjames** [comment]
Hmm, this looks like minor corruption which might have happened during a version migration. Try removing all networks from Scatter and then re-adding them since it seems like a network reference is busted.

**Comment by nsjames** [comment]
Closing due to lack of more information and follow up

**Comment by caniko2** [comment]
Hi, I have the same issue. It didn't work by removing and re-adding the respective network.
