### ISSUE TITLE
Cannot display account settings

### ISSUE THREAD

**Issue by MrToph** [GetScatter/ScatterDesktop#38]
When I try to visit the Account settings of an accout for a local node network, it crashes and doesn't render anything in the account info tab.

This is the network setting:
```
EOS localhost
127.0.0.1
8888
http
chainId: cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f
```

These 3 errors are being shown:
```js
vue.esm.js:1741 TypeError: Cannot read property 'id' of undefined
    at s.isEndorsedNetwork (Keypair.vue:226)
    at Keypair.vue?dc76:1
    at s.qe [as _l] (vue.esm.js:3705)
    at s.render (Keypair.vue?dc76:1)
    at s.t._render (vue.esm.js:4544)
    at s.r (vue.esm.js:2788)
    at Oe.get (vue.esm.js:3142)
    at Oe.run (vue.esm.js:3219)
    at Te (vue.esm.js:2981)
    at Array.<anonymous> (vue.esm.js:1837)
Kt @ vue.esm.js:1741
Ht @ vue.esm.js:1732
zt @ vue.esm.js:1721
t._render @ vue.esm.js:4546
r @ vue.esm.js:2788
Oe.get @ vue.esm.js:3142
Oe.run @ vue.esm.js:3219
Te @ vue.esm.js:2981
(anonymous) @ vue.esm.js:1837
Gt @ vue.esm.js:1758


vue.esm.js:1741 TypeError: Cannot read property 'id' of undefined
    at s.isEndorsedNetwork (Keypair.vue:226)
    at Keypair.vue?dc76:1
    at s.qe [as _l] (vue.esm.js:3705)
    at s.render (Keypair.vue?dc76:1)
    at s.t._render (vue.esm.js:4544)
    at s.r (vue.esm.js:2788)
    at Oe.get (vue.esm.js:3142)
    at Oe.run (vue.esm.js:3219)
    at Te (vue.esm.js:2981)
    at Array.<anonymous> (vue.esm.js:1837)
Kt @ vue.esm.js:1741
Ht @ vue.esm.js:1732
zt @ vue.esm.js:1721
t._render @ vue.esm.js:4546
r @ vue.esm.js:2788
Oe.get @ vue.esm.js:3142
Oe.run @ vue.esm.js:3219
Te @ vue.esm.js:2981
(anonymous) @ vue.esm.js:1837
Gt @ vue.esm.js:1758
Async Call
$t @ vue.esm.js:1806
te @ vue.esm.js:1850
(anonymous) @ vue.esm.js:3068
Oe.update @ vue.esm.js:3209
ft.notify @ vue.esm.js:697
(anonymous) @ vue.esm.js:844
(anonymous) @ Keypair.vue:216
_ @ runtime.js:62
(anonymous) @ runtime.js:296
t.(anonymous function) @ runtime.js:114
n @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
n @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
e @ _export.js:36
(anonymous) @ asyncToGenerator.js:14
(anonymous) @ Keypair.vue:213
mounted @ Keypair.vue:213
Ae @ vue.esm.js:2921
insert @ vue.esm.js:4158
e @ vue.esm.js:2023
x @ vue.esm.js:5960
t.nodeOps @ vue.esm.js:6179
t._update @ vue.esm.js:2670
r @ vue.esm.js:2788
Oe.get @ vue.esm.js:3142
Oe.run @ vue.esm.js:3219
Te @ vue.esm.js:2981
(anonymous) @ vue.esm.js:1837
Gt @ vue.esm.js:1758


eos.js:120 Uncaught (in promise) TypeError: Cannot read property 'fullhost' of undefined
    at a.<anonymous> (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/app.b04a080cb563f1ad3912.js:1:452385)
    at _ (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/vendor.d04dfa4af3759d05a956.js:43:73716)
    at Generator._invoke (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/vendor.d04dfa4af3759d05a956.js:43:73504)
    at Generator.t.(anonymous function) [as next] (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/vendor.d04dfa4af3759d05a956.js:43:73895)
    at n (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/vendor.d04dfa4af3759d05a956.js:68:182858)
    at file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/vendor.d04dfa4af3759d05a956.js:68:182999
    at new Promise (<anonymous>)
    at new e (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/vendor.d04dfa4af3759d05a956.js:86:67061)
    at a.<anonymous> (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/vendor.d04dfa4af3759d05a956.js:68:182793)
    at a.b.value (file:///<censored>/Scatter%20Desktop/resources/app.asar/dist/static/js/app.b04a080cb563f1ad3912.js:1:452616)
```

**Comment by nsjames** [comment]
Ah, looks like you might have encountered a bug that is already fixed but still not in the latest build yet. 

Did you perhaps delete a network recently?

**Comment by nsjames** [comment]
507eadb7f76bbfaa97f0a1a7ac76214ef9bf2cf0
