### ISSUE TITLE
Linux release build missing babel-polyfill

### ISSUE THREAD

**Issue by jcalfee** [GetScatter/ScatterDesktop#394]
After a successful `npm run release-linux` on v11, running the AppImage produces this runtime error below.  A UI window appears but it is all white and has no UI elements in it.

```bash
$ ./opt/linux-scatter-11.0.0-x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'babel-polyfill'
Require stack:
- /tmp/.mount_linux-0YMMlR/resources/app.asar/electron.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:659:15)
    at Function.Module._resolveFilename (/tmp/.mount_linux-0YMMlR/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:577:27)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/tmp/.mount_linux-0YMMlR/resources/app.asar/electron.js:271:1)
    at Module._compile (internal/modules/cjs/loader.js:808:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
```
UI Screen shot:
![image](https://user-images.githubusercontent.com/204121/60126661-1791f800-9754-11e9-92c1-409171e28cdf.png)

**Comment by jcalfee** [comment]
Solved by using yarn instead of NPM .. related: https://github.com/GetScatter/ScatterDesktop/issues/392
