### ISSUE TITLE
Cannot find certificate GetScatter Ltd

### ISSUE THREAD

**Issue by dp1993132** [GetScatter/ScatterDesktop#478]
Cannot find certificate GetScatter Ltd., all certs:   stackTrace=
                                                            Error: Cannot find certificate GetScatter Ltd., all certs: 
                                                                at getCertificateFromStoreInfo (/Users/mac/Desktop/work/ScatterDesktop/node_modules/app-builder-lib/src/codeSign/windowsCodeSign.ts:142:9)
                                                                at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dp1993132** [comment]
mac compile win32/amd64, not work

**Comment by nsjames** [comment]
If you want to build yourself, you'll have to remove code signing since you don't have access to our certs.
