### ISSUE TITLE
Unable to start in development mode on OSX

### ISSUE THREAD

**Issue by Soleone** [GetScatter/ScatterDesktop#498]
Trying to run ScatterDesktop in development mode on OSX (Catalina 10.15.4), but getting an error I can't quite figure out right now.

I don't seem to have the node and electron version installed that is recommended in the readme.

Do I need something like a node version manager? Any recommendations for next steps? Thanks!

```
➜ yarn install

yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ electron-rebuild
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.0.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/tiny-secp256k1/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/soleone/.electron-gyp/5.0.13/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/soleone/.electron-gyp/5.0.13',
gyp info spawn args   '-Dnode_gyp_dir=/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/soleone/.electron-gyp/5.0.13/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/tiny-secp256k1',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/secp256k1/native/addon.o
../native/addon.cpp:18:1: error: unknown type name 'secp256k1_context'; did you mean 'secp256k1_context_t'?
secp256k1_context* context;
^~~~~~~~~~~~~~~~~
secp256k1_context_t
/usr/local/include/secp256k1.h:50:41: note: 'secp256k1_context_t' declared here
typedef struct secp256k1_context_struct secp256k1_context_t;
                                        ^
../native/addon.cpp:54:28: error: unknown type name 'secp256k1_pubkey'
        bool isPoint (const T& x, secp256k1_pubkey& pubkey) {
                                  ^
../native/addon.cpp:65:32: error: unknown type name 'secp256k1_ecdsa_signature'
        bool isSignature (const T& x, secp256k1_ecdsa_signature& signature) {
                                      ^
../native/addon.cpp:71:45: error: unknown type name 'secp256k1_pubkey'
        v8::Local<v8::Object> pointAsBuffer (const secp256k1_pubkey& public_key, const uint32_t flags) {
                                                   ^
../native/addon.cpp:80:63: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                            ^
../native/addon.cpp:80:89: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                                                      ^
../native/addon.cpp:81:42: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info[index]->IsUndefined()) return SECP256K1_EC_COMPRESSED;
                                                       ^
../native/addon.cpp:83:65: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                              ^
../native/addon.cpp:83:91: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                                                        ^
../native/addon.cpp:91:38: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                                                   ^
../native/addon.cpp:92:42: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info[index]->IsUndefined()) return SECP256K1_EC_COMPRESSED;
                                                       ^
../native/addon.cpp:94:65: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                              ^
../native/addon.cpp:94:91: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                                                        ^
../native/addon.cpp:108:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:119:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:142:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey a, b;
        ^
../native/addon.cpp:144:19: error: use of undeclared identifier 'b'
        if (!isPoint(pB, b)) return THROW_BAD_POINT;
                         ^
../native/addon.cpp:146:8: error: unknown type name 'secp256k1_pubkey'
        const secp256k1_pubkey* points[] = { &a, &b };
              ^
../native/addon.cpp:146:44: error: use of undeclared identifier 'b'
        const secp256k1_pubkey* points[] = { &a, &b };
                                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.0.0/bin/node" "/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=5.0.13" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/soleone/workspace/opensource/ScatterDesktop/node_modules/tiny-secp256k1
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@14.0.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/tiny-secp256k1/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/soleone/.electron-gyp/5.0.13/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/soleone/.electron-gyp/5.0.13',
gyp info spawn args   '-Dnode_gyp_dir=/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/soleone/.electron-gyp/5.0.13/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/tiny-secp256k1',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/secp256k1/native/addon.o
../native/addon.cpp:18:1: error: unknown type name 'secp256k1_context'; did you mean 'secp256k1_context_t'?
secp256k1_context* context;
^~~~~~~~~~~~~~~~~
secp256k1_context_t
/usr/local/include/secp256k1.h:50:41: note: 'secp256k1_context_t' declared here
typedef struct secp256k1_context_struct secp256k1_context_t;
                                        ^
../native/addon.cpp:54:28: error: unknown type name 'secp256k1_pubkey'
        bool isPoint (const T& x, secp256k1_pubkey& pubkey) {
                                  ^
../native/addon.cpp:65:32: error: unknown type name 'secp256k1_ecdsa_signature'
        bool isSignature (const T& x, secp256k1_ecdsa_signature& signature) {
                                      ^
../native/addon.cpp:71:45: error: unknown type name 'secp256k1_pubkey'
        v8::Local<v8::Object> pointAsBuffer (const secp256k1_pubkey& public_key, const uint32_t flags) {
                                                   ^
../native/addon.cpp:80:63: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                            ^
../native/addon.cpp:80:89: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                                                      ^
../native/addon.cpp:81:42: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info[index]->IsUndefined()) return SECP256K1_EC_COMPRESSED;
                                                       ^
../native/addon.cpp:83:65: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                              ^
../native/addon.cpp:83:91: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                                                        ^
../native/addon.cpp:91:38: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                                                   ^
../native/addon.cpp:92:42: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                if (info[index]->IsUndefined()) return SECP256K1_EC_COMPRESSED;
                                                       ^
../native/addon.cpp:94:65: error: use of undeclared identifier 'SECP256K1_EC_COMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                              ^
../native/addon.cpp:94:91: error: use of undeclared identifier 'SECP256K1_EC_UNCOMPRESSED'
                return info[index]->BooleanValue(v8::Isolate::GetCurrent()) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UNCOMPRESSED;
                                                                                                        ^
../native/addon.cpp:108:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:119:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey public_key;
        ^
../native/addon.cpp:142:2: error: unknown type name 'secp256k1_pubkey'
        secp256k1_pubkey a, b;
        ^
../native/addon.cpp:144:19: error: use of undeclared identifier 'b'
        if (!isPoint(pB, b)) return THROW_BAD_POINT;
                         ^
../native/addon.cpp:146:8: error: unknown type name 'secp256k1_pubkey'
        const secp256k1_pubkey* points[] = { &a, &b };
              ^
../native/addon.cpp:146:44: error: use of undeclared identifier 'b'
        const secp256k1_pubkey* points[] = { &a, &b };
                                                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/secp256k1/native/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/usr/local/Cellar/node/14.0.0/bin/node" "/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=5.0.13" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd /Users/soleone/workspace/opensource/ScatterDesktop/node_modules/tiny-secp256k1
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/rxjs/internal/Subscriber.js:143:22)
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```
~/workspace/opensource/ScatterDesktop(master) ➜ electron .
App threw an error during load
/Users/soleone/workspace/opensource/ScatterDesktop/node_modules/electron-store/index.js:12
			...options
			^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/soleone/workspace/opensource/ScatterDesktop/electron/services/storage.js:1:170)
^C
```

```
~/workspace/opensource/ScatterDesktop(master) ➜ node -v
v14.0.0
```

```
~/workspace/opensource ➜ yarn -v
1.22.4
```

```
~/workspace/opensource ➜ electron -v
v1.8.3
```

```
~/workspace/opensource ➜ python -v

...

WARNING: Python 2.7 is not recommended.
This version is included in macOS for compatibility with legacy software.
Future versions of macOS will not include Python 2.7.
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Feb 29 2020, 01:55:37)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin

...
```

**Comment by Soleone** [comment]
Update: Tried installing node version manager `n`, and python version manager `pyenv` but didn't seem to help with that error.

```
~/workspace/opensource/ScatterDesktop(master*) ➜ node -v
v10.15.3
```

```
~/workspace/opensource/ScatterDesktop(master*) ➜ npm -v
6.4.1
```

```
~/workspace/opensource/ScatterDesktop(master*) ➜ python --version
Python 3.7.7
```

**Comment by Soleone** [comment]
Looks like I fixed the issue by manually installing `secp256k1`:

```
 brew tap domt4/crypto
```

```
brew install secp256k1
```

Which gave me this warning:

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/secp256k1.h
Target /usr/local/include/secp256k1.h
already exists. You may want to remove it:
  rm '/usr/local/include/secp256k1.h'

To force the link and overwrite all conflicting files:
  brew link --overwrite secp256k1

To list all files that would be deleted:
  brew link --overwrite --dry-run secp256k1

Possible conflicting files are:
/usr/local/include/secp256k1.h
/usr/local/lib/libsecp256k1.0.dylib
/usr/local/lib/libsecp256k1.a
/usr/local/lib/libsecp256k1.dylib -> /usr/local/lib/libsecp256k1.0.dylib
/usr/local/lib/pkgconfig/libsecp256k1.pc
```

Which I tried to address via:

```
brew link --overwrite secp256k1
```

Afterwards `yarn install` seemed to succeed:

```
~/workspace/opensource/ScatterDesktop(master*) ➜ yarn install
yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ electron-rebuild
✔ Rebuild Complete
✨  Done in 20.89s.
```

**Comment by Soleone** [comment]
~~Now I am stuck trying to launch `electron .` though, will try to update this issue after more investigation.~~

Running `electron .` always caused this error:

```
/Users/dennistheisen/workspace/opensource/ScatterDesktop/node_modules/usb/build/Release/usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

Full output:

```
~/workspace/opensource/ScatterDesktop(master*) ➜ ./node_modules/.bin/electron .
App threw an error during load
Error: The module '/Users/dennistheisen/workspace/opensource/ScatterDesktop/node_modules/usb/build/Release/usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (/Users/dennistheisen/workspace/opensource/ScatterDesktop/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/dennistheisen/workspace/opensource/ScatterDesktop/node_modules/usb/usb.js:1:57)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
There was an uncaught error Error: The module '/Users/dennistheisen/workspace/opensource/ScatterDesktop/node_modules/usb/build/Release/usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (/Users/dennistheisen/workspace/opensource/ScatterDesktop/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/dennistheisen/workspace/opensource/ScatterDesktop/node_modules/usb/usb.js:1:57)
    at Module._compile (internal/modules/cjs/loader.js:839:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:851:10)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
```

I tried switching back to lts version of node via:

```
n lts
```

(might require sudo depending on your environment)

```
sudo n lts
```

Afterwards it was using this version of node:

```
~/workspace/opensource/ScatterDesktop(master*) ➜ node -v
v12.16.2
```

Running `yarn install` again worked now even with this node version:

```
~/workspace/opensource/ScatterDesktop(master*) ➜ yarn install
yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "@walletpack/ethereum > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime@7.9.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > mini-css-extract-plugin@0.8.2" has unmet peer dependency "webpack@^4.4.0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ electron-rebuild
✔ Rebuild Complete
✨  Done in 58.37s.
```

And finally success launching the full desktop app:

```
➜ ./node_modules/.bin/electron .
```

**Comment by Soleone** [comment]
Resolved
