### ISSUE TITLE
won"t install on Mint 18.2 cinnamon

### ISSUE THREAD

**Issue by StevenAbaby** [GetScatter/ScatterDesktop#60]
sudo ./linux-scatter-8.9.0-x86_64.AppImage 
[sudo] password for steve: 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.pKAHT4: invalid ELF header
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_linux-w9OM2H/resources/app.asar/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/tmp/.mount_linux-w9OM2H/resources/app.asar/node_modules/usb/usb.js:417:3)

**Comment by nsjames** [comment]
Referencing this ticket and closing https://github.com/GetScatter/ScatterDesktop/issues/61
