### ISSUE TITLE
Scatter 8.9.0 uncaught exception ( Ubuntu / Linux Builds )

### ISSUE THREAD

**Issue by javierjmc** [GetScatter/ScatterDesktop#61]
I get this when starting the app.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.XrJQSK: invalid ELF header
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_linux-qbFUpf/resources/app.asar/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/tmp/.mount_linux-qbFUpf/resources/app.asar/node_modules/usb/usb.js:417:3)
```
Here is my system's info:

$ uname -a
Linux 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nsjames** [comment]
Hmm, it looks like possibly the download got corrupted somewhere. 
Try downloading it again and re-installing. Let's see if that helps.

**Comment by AdvancedStyle** [comment]
Same issue on 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by Mustard5** [comment]
Won't install on Mint 19 Cinnamon either.  Same error message when run from console.
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.NQ2zkH: invalid ELF header
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_linux-Mz6zFr/resources/app.asar/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/tmp/.mount_linux-Mz6zFr/resources/app.asar/node_modules/usb/usb.js:417:3)
`

**Comment by NavidGoalpure** [comment]
same issue on 
Ubuntu 16.04.5 LTS 64-bit

**Comment by nsjames** [comment]
For now please use 8.8.0. 
The nest release will fix the build error in the Linux release.

**Comment by plouto5** [comment]
getting the same result with:
╰─$ uname -rm
4.14.70-1-MANJARO x86_64

**Comment by Lamaw** [comment]
Same issue on **Scatter Desktop 9.0.0** with ubuntu 16.04 -> 4.4.0-134-generic x86_64

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.tnZVII: invalid ELF header
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_linux-aiM84i/resources/app.asar/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/tmp/.mount_linux-aiM84i/resources/app.asar/node_modules/usb/usb.js:417:3)

Anything I can do ?

**Comment by nsjames** [comment]
Hey guys check the latest build and let me know.

**Comment by Lamaw** [comment]
The last build fix the issue here.
Thanks!
